#!/bin/bash
set -x
bash clean.sh

# ----- scientific_writing talk -------
name=scientific_writing

# Note: since Doconce syntax is demonstrated inside !bc/!ec
# blocks we need a few fixes

doconce format html $name --pygments_html_style=native --keep_pygments_html_bg
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce slides_html $name reveal --html_slide_theme=darkgray
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
cp $name.html ${name}_reveal.html

function editfix {
# Fix selected backslashes inside verbatim envirs that doconce has added
# (only a problem when we want to show full doconce code with
# labels in !bc-!ec envirs).
doconce replace '\label{this:section}' 'label{this:section}' $1
doconce replace '\label{fig1}' 'label{fig1}' $1
doconce replace '\label{demo' 'label{demo' $1
doconce replace '\eqref{eq1}' '(ref{eq1})' $1
doconce replace '\eqref{myeq}' '(ref{myeq})' $1
doconce replace '\eqref{mysec:eq:Dudt}' '(ref{mysec:eq:Dudt})' $1
}

editfix ${name}_reveal.html


doconce format html $name --pygments_html_style=perldoc --keep_pygments_html_bg
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
cp $name.html ${name}_deck.html
doconce slides_html ${name}_deck deck --html_slide_theme=sandstone.default
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
editfix ${name}_deck.html

# Plain HTML documents
doconce format html $name --pygments_html_style=perldoc --html_style=solarized --html_admon=apricot
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
cp $name.html ${name}_solarized.html
editfix ${name}_solarized.html

doconce format html $name --pygments_html_style=default
cp $name.html ${name}_plain.html
editfix ${name}_plain.html
doconce split_html ${name}_plain.html
# Remove top navigation in all parts
doconce subst -s '<!-- begin top navigation.+?end top navigation -->' '' ${name}_plain.html ._part*_${name}*.html

# LaTeX Beamer slides
doconce format pdflatex $name
editfix ${name}.p.tex
doconce ptex2tex $name -DLATEX_HEADING=beamer envir=minted
doconce slides_beamer $name --beamer_slide_theme=red_shadow
cp $name.tex ${name}_red_shadow.tex
pdflatex -shell-escape ${name}_red_shadow

# LaTeX documents
doconce format pdflatex $name --minted_latex_style=trac
editfix ${name}.p.tex
doconce ptex2tex $name envir=minted -DBOOK
doconce replace 'section{' 'section*{' $name.tex
pdflatex -shell-escape $name
mv -f $name.pdf ${name}_minted.pdf

doconce format pdflatex $name
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
editfix ${name}.p.tex
doconce replace 'section{' 'section*{' ${name}.p.tex
doconce ptex2tex $name envir=ans:nt -DBOOK
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
pdflatex $name
mv -f $name.pdf ${name}_anslistings.pdf

# sphinx doesn't handle math inside code well, we drop it since
# other formats demonstrate doconce writing this way
doconce format sphinx $name
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
editfix ${name}.rst
doconce sphinx_dir author="H. P. Langtangen" theme=pyramid $name
python automake_sphinx.py

doconce format pandoc $name  # Markdown (pandoc extended)
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce format gwiki  $name  # Googlecode wiki
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi

# These don't like slides with code after heading:
#doconce format rst    $name  # reStructuredText
#doconce format plain  $name  # plain, untagged text for email

pygmentize -l text -f html -o ${name}_doconce.html ${name}.do.txt

dest=../../pub/slides

cp -r ${name}*.pdf ._part*_${name}_*.html *.md *.gwiki ${name}*.html deck.js reveal.js fig $dest/

doconce format html sw_index.do.txt
cp sw_index.html $dest/index.html

# --------- short demo talk ------------

doconce format html demo SLIDE_TYPE=dummy SLIDE_THEME=dummy # test
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi

# Make all the styles for the short demo talk
doconce slides_html demo all  # generates tmp_slides_html_all.sh
pygmentize -l text -f html -o demo_doconce.html demo.do.txt
sh -x tmp_slides_html_all.sh

# LaTeX Beamer slides
themes="blue_plain blue_shadow red_plain red_shadow cbc simula"
beamer_pdfs=""
for theme in $themes; do
doconce format pdflatex demo SLIDE_TYPE="beamer" SLIDE_THEME="$theme"
doconce ptex2tex demo -DLATEX_HEADING=beamer envir=minted
doconce slides_beamer demo --beamer_slide_theme=$theme
cp demo.tex demo_${theme}.tex
pdflatex -shell-escape demo_${theme}
beamer_pdfs="$beamer_pdfs <a href=\"demo_$theme.pdf\">$theme</a>"
done

# LaTeX document
doconce format pdflatex demo SLIDE_TYPE="latex document" SLIDE_THEME="no theme"
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
doconce ptex2tex demo -DPALATINO envir=minted
if [ $? -ne 0 ]; then echo "make.sh: abort"; exit 1; fi
pdflatex -shell-escape demo

cp -r demo*.pdf demo_*.html reveal.js deck.js csss fig $dest/demo/
cat > $dest/demo/index.html <<EOF
<h1>Autogenerated slide styles</h1>
<b>Note:</b>

These slides are normally best viewed in Firefox in full screen mode,
but some functionality in reveal works in Chrome and not in Firefox.
Bring slide shows up in separate tabs. You may need to reload some
pages to get the mathematics correctly rendered.

<ul>
<p><li> reveal.js: (the css style files are slightly changed: left-adjusted,
lower case headings with smaller fonts; "darkgray" corresponds to
the original "default" theme)
<ul>
<p><li><a href="demo_reveal_beige.html">reveal, beige theme</a>
<pre>
doconce format html demo --pygments_html_style=perldoc --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=beige
doconce slides_html demo reveal --html_slide_theme=beige
</pre>
(Note that <tt>SLIDE_TYPE</tt> and <tt>SLIDE_THEME</tt> are user-defined Mako variables used in the <tt>demo.do.txt</tt> file - they are very specific to these slides and other presentations will most likely not use such variables, but perhaps others.)
<li><a href="demo_reveal_beigesmall.html">reveal, beigesmall theme</a>
<pre>
doconce format html demo --pygments_html_style=perldoc --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=beigesmall
doconce slides_html demo reveal --html_slide_theme=beigesmall
</pre>
<li><a href="demo_reveal_darkgray.html">reveal, darkgray theme</a>
<pre>
doconce format html demo --pygments_html_style=native --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=darkgray
doconce slides_html demo reveal --html_slide_theme=darkgray
</pre>
<li><a href="demo_reveal_serif.html">reveal, serif theme</a>
<pre>
doconce format html demo --pygments_html_style=perldoc --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=serif
doconce slides_html demo reveal --html_slide_theme=serif
</pre>
<li><a href="demo_reveal_night.html">reveal, night theme</a>
<pre>
doconce format html demo --pygments_html_style=fruity --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=night
doconce slides_html demo reveal --html_slide_theme=night
</pre>
<li><a href="demo_reveal_simple.html">reveal, simple theme</a>
<pre>
doconce format html demo --pygments_html_style=autumn --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=simple
doconce slides_html demo reveal --html_slide_theme=simple
</pre>
<li><a href="demo_reveal_sky.html">reveal, sky theme</a>
</ul>
<p><li> deck.js: (the css styles are slightly changed, mainly somewhat
smaller fonts for verbatim code)
<ul>
<p><li><a href="demo_deck_beamer.html">deck, beamer theme</a>
<pre>
doconce format html demo --pygments_html_style=autumn --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=beamer
doconce slides_html demo deck --html_slide_theme=beamer
</pre>
<li><a href="demo_deck_mnml.html">deck, mnml theme</a>
<pre>
doconce format html demo --pygments_html_style=default --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=mnml
doconce slides_html demo deck --html_slide_theme=mnml
</pre>
<li><a href="demo_deck_neon.html">deck, neon theme</a>
<pre>
doconce format html demo --pygments_html_style=fruity --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=neon
doconce slides_html demo deck --html_slide_theme=neon
</pre>
<li><a href="demo_deck_sandstone_aurora.html">deck, sandstone.aurora theme</a>
<pre>
doconce format html demo --pygments_html_style=fruity --keep_pygments_html_bg    SLIDE_TYPE=deck SLIDE_THEME=sandstone-aurora
doconce slides_html demo deck --html_slide_theme=sandstone.aurora
</pre>
<li><a href="demo_deck_sandstone_dark.html">deck, sandstone.dark theme</a>
<pre>
doconce format html demo --pygments_html_style=native --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=sandstone.dark
doconce slides_html demo deck --html_slide_theme=sandstone.dark
</pre>
<li><a href="demo_deck_sandstone_default.html">deck, sandstone.default theme</a>
<pre>
doconce format html demo --pygments_html_style=perldoc --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=sandstone.default
doconce slides_html demo deck --html_slide_theme=sandstone.default
</pre>
<li><a href="demo_deck_sandstone_firefox.html">deck, sandstone.firefox theme</a>
<pre>
doconce format html demo --pygments_html_style=default --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=sandstone.firefox
doconce slides_html demo deck --html_slide_theme=sandstone.firefox
</pre>
<li><a href="demo_deck_sandstone_light.html">deck, sandstone.light theme</a>
<li><a href="demo_deck_sandstone_mdn.html">deck, sandstone.mdn theme</a>
<pre>
doconce format html demo --pygments_html_style=emacs --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=sandstone.light
doconce slides_html demo deck --html_slide_theme=sandstone.light
</pre>
<li><a href="demo_deck_sandstone_mightly.html">deck, sandstone.mightly theme</a>
<pre>
doconce format html demo --pygments_html_style=fruity --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=sandstone.mightly
doconce slides_html demo deck --html_slide_theme=sandstone.mightly
</pre>
<li><a href="demo_deck_swiss.html">deck, swiss theme</a>
<pre>
doconce format html demo --pygments_html_style=autumn --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=swiss
doconce slides_html demo deck --html_slide_theme=swiss
</pre>
<li><a href="demo_deck_web-2_0.html">deck, web-2_0 theme</a>
<pre>
doconce format html demo --pygments_html_style=autumn --keep_pygments_html_bg SLIDE_TYPE=deck SLIDE_THEME=web-2.0
doconce slides_html demo deck --html_slide_theme=web-2.0
</pre>
</ul>
<li><a href="demo_dzslides_dzslides_default.html">dzslides</a>
<pre>
doconce format html demo --pygments_html_style=autumn --keep_pygments_html_bg SLIDE_TYPE=dzslides SLIDE_THEME=dzslides_default
doconce slides_html demo dzslides --html_slide_theme=dzslides_default
</pre>
<li><a href="demo_csss_csss_default.html">csss</a> (black background instead
of the original rainbow background)
<pre>
doconce format html demo --pygments_html_style=monokai --keep_pygments_html_bg SLIDE_TYPE=csss SLIDE_THEME=csss_default
doconce slides_html demo csss --html_slide_theme=csss_default
</pre>
<li>LaTeX Beamer PDF: $beamer_pdfs
<pre>
doconce format pdflatex demo SLIDE_TYPE="beamer" SLIDE_THEME="red_shadow"
doconce ptex2tex demo -DLATEX_HEADING=beamer envir=minted
doconce slides_beamer demo --beamer_slide_theme=red_shadow
pdflatex -shell-escape demo
cp demo.pdf demo_red_shadow.pdf
</pre>
<li><a href="demo.pdf">Handouts in PDF</a> (generated via LaTeX)
<pre>
doconce format pdflatex demo SLIDE_TYPE="latex" SLIDE_THEME="std. latex"
doconce ptex2tex demo envir=minted
pdflatex -shell-escape demo
</pre>
<li><a href="demo_doconce.html">Doconce source code for the slides</a>
<li>Doconce: Why and How,
<a href="../scientific_writing_reveal.html">reveal w/darkgrey</a>,
<a href="../scientific_writing_deck.html">deck w/sandstone.default</a>,
<a href="../scientific_writing_red_shadow.pdf">beamer</a>,
<a href="../scientific_writing_solarized.html">solarized</a>,
<a href="../scientific_writing_solarized">plain HTML</a>
</ul>
EOF