#!/bin/sh
# clean up all files that are easily regenerated by the make.sh script

name=docstring
files="*~ log.log ${name}*.dst.txt ${name}*.html $name.txt ${name}*.tex ${name}_rst.* $name.rst $name.sphinx.rst $name.odt $name.st $name.epytext $name.wiki __tmp.do.txt ._tmp.do.txt ${name}*.ps ${name}*.pdf _*.log *.*xml *.aux ${name}*.log ${name}*.dvi *.out sphinx-rootdir"
dir=`pwd`
echo "Removing in $dir:"
/bin/ls $files 2> /dev/null
rm -rf $files
