.TH "DOCONCE" 1

.SH NAME
doconce - run a Doconce command

.SH SYNOPSIS
.B doconce
command
[\fIOPTIONS\fR]

.SH DESCRIPTION
The \fBdoconce\fR script takes a command and runs a corresponding
utility. Run the script without arguments to see a list of available
commands.

.SH BUGS
.TP
Send comments, questions, bug reports etc. to doconce@googlegroups.com.

.SH LICENSE
Doconce is licensed under the new BSD license.

.SH AUTHOR
Doconce is mainly written by Hans Petter Langtangen <hpl@simula.no>, with
contributions from Johannes H. Ring <johannr@simula.no>.
